### ISSUE TITLE
Default representation option

### ISSUE THREAD

**Issue by SebastianMars** [ogametracker/ogame-extension#205]
I would like to suggest a new Option under Accessability in the Settings.  
A Option to set the default representation of the collected information for things like expeditions, resources etc.  
The Option should make it possible to show information in the table style as default instead of the not accessible diagramm view.  
I am visiualy impared and that would be really nice.

**Comment by backfromexile** [comment]
Hey there, it's not very obvious, but you can right click any menu item or menu tab to set it as the default for the selected section
